### ISSUE TITLE
Option to launch specific app on boot as a background service

### ISSUE THREAD

**Issue by pranavg189** [ITVlab/Launch-On-Boot#11]
It would be great if apps can be started as background service rather than launching the app UI on bootup.

**Comment by Fleker** [comment]
Is there a good use case for this? If the app is to launch as a service,
that could be done within that specific app

**Comment by pranavg189** [comment]
Hmm..you are right...runnning the app as background service needs to be implemented within that app itself...I assumed there was some way to hide the app UI that gets shown on bootup. btw, "Launch on Boot" is a very convenient app for me to launch apps like Youtube or Termux on startup. Thanks !
