### ISSUE TITLE
Publishing on F-Droid?

### ISSUE THREAD

**Issue by sgtpep** [ITVlab/Launch-On-Boot#16]
Hi there! Thank you for this great and indispensable peace of software. It's the only one I've found which is open-source and could launch an app on boot, not counting Termux:Boot which has the WAKE_LOCK permission for some reason that prevents the device from sleeping.

It would be really nice to be able to download this app from F-Droid, although I realize it involves some bureaucracy no one wanna deal with, but still it would be great in many ways. Thank you, anyway!

**Comment by Fleker** [comment]
Is there an advantage to using F-Droid? It's already on Google Play.

**Comment by sgtpep** [comment]
I don't know how to convince developers to publish their apps on F-Droid, but to me, as a FOSS user, apps from there are preferred, because it's guaranteed that compiled app corresponds to its source code and doesn't contain some unwanted things like tracking, etc. Dunno, installing apps from Google Play feels like installing shareware proprietary apps from 90's, while installing apps from F-Droid feels like installing packages from Debian repository that are robust, stable and trustworthy.

**Comment by Fleker** [comment]
Seems like a fine idea. I'll work on this over the weekend.

**Comment by sgtpep** [comment]
That is awesome! Very much appreciated.

**Comment by IzzySoft** [comment]
@Fleker could you please take a look at the latest tag? It claims to be 1.1.2 – but the `build.gradle` behind the tag still shows 1.1.1. Guess it was you opening [the RFP](https://gitlab.com/fdroid/rfp/issues/876) – so no need to ask whether you agree in general 😉 Looks good so far, except for the tat.

**Comment by Fleker** [comment]
@IzzySoft I haven't changed anything in a while, so I just changed the build.gradle to match what the releases are at.

**Comment by IzzySoft** [comment]
Thanks @Fleker – now we only need the tag pointing there :smiley:

**Comment by Fleker** [comment]
@IzzySoft I've moved everything to 1.1.3 to get the releases tab and the project in sync.

**Comment by IzzySoft** [comment]
@Fleker Thanks, updated that at our end. But you again forgot to increase versionCode (which is at `12` at least since v1.1.1). Might not be a big issue as long your app was not yet added to F-Droid – but once it is and you forgot again, that update wouldn't reach us. `versionCode` ***must*** be updated with each release. `versionName` ***should.***

**Comment by Fleker** [comment]
Thanks for the information. As these changes were just catching up the two properties, and not a release, I didn't think about changing the version code. Future changes will be released via Google Play as well, and that will also enforce unique version codes.

**Comment by TPS** [comment]
@sgtpep @Fleker @IzzySoft v1.1.3 is now [natively available on F-Droid](https://f-droid.org/app/news.androidtv.launchonboot), so this issue can be closed (resolved). 🙇🏾‍♂️
