### ISSUE TITLE
Requirements for Launch when device wakes up

### ISSUE THREAD

**Issue by hoasis2** [ITVlab/Launch-On-Boot#19]
What are the requirements for launch on wake up to work?

Unfortunately there is hardly any documentation about it. You can't even see "Launch when device wakes up" option on the screenshots.

I've testet 1.1.3 from F-Droid on ATV 7.0.
Launch on boot works fine, but on wake up does not work at all.

**Comment by Fleker** [comment]
The app receives an event when a screensaver exits or the device just booted.

**Comment by hoasis2** [comment]
So if I understood it correctly, the screensaver must be running on the TV just when I put it into standby mode, isn't it?

**Comment by Fleker** [comment]
If there's no screensaver, there is no way for the app to know when the device has woken up.

**Comment by hoasis2** [comment]
Thank you! :)
